### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by wrathematics** [thecodingdoc/neep#2]
Hi, I'm reviewing your submission for JOSS. This isn't strictly necessary, but would you consider using a Makefile? Here's a sample I used which you may freely take if you like:

```make
CXX = g++
CXXFLAGS = -O3 -std=c++11
OMPFLAGS = -fopenmp
WARNFLAGS = -Wall -pedantic -Wextra


all: neep

SRCS=$(wildcard *.C)
OBJS=$(SRCS:.C=.o )

%.o: %.C
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) $(WARNFLAGS) $(OMPFLAGS) -c $< -o $@

neep: $(OBJS)
	$(CXX) $(OBJS) -o neep $(OMPFLAGS)

clean:
	rm -rf *.o neep
```

**Comment by scwest** [comment]
I'll make one and have it committed by tomorrow.

Sean West
GitHub: scwest

**Comment by scwest** [comment]
The Makefile has been added. Thank you for your suggestion and also the filled template for writing the Makefile. I used it with a comment within the Makefile indicating that it came from you.
