### ISSUE TITLE
JOSS Pre-edits and Suggestions

### ISSUE THREAD

**Issue by rhagenson** [thecodingdoc/neep#4]
All the edits I see necessary prior to JOSS acceptance:

- [x] Add a plaintext LICENSE file with an [OSI approved](https://opensource.org/licenses/alphabetical) license
- [x] Fix the authorship disconnect of commits by `swest` and the actual account `scwest` (missing/added 'c' in name)
- [x] Add a Makefile for the standard make -> make check/test -> make install/build workflow
- [ ] Set up continuous integration/testting to automate testing upon new commits (recommendation is either Travis or Github Actions as they are fairly easy to set up)
- [x] Fix the references in the article proof (IDs must be the case case as in the .bib so are disconnected) then run `@whedon generate pdf` in the review issue; you can use http://whedon.theoj.org/ to test the rendering prior to regenerating the proof in the review issue
- [x] The URL https://nebraska.edu/collaborationinitiative should be https://nebraska.edu/collaboration-initiative and not end with a slash 

Suggested changes:

- [x] Move the contributing.md content to the end of the README as a section and make support go through Github issues rather than email so that others with similar problems can view the old solutions within closed issues
- [x] Consider a license other than GPL (I am adamantly anti-GPL and refuse to use any Bioinformatics code licensed under it)
- [x] You specify the full name for all acronyms in the paper except FDR which you could reasonably treat the same as all other acronyms
- [x] You specify both CPH and Cox-PH in the paper, this should be consistently one or the other
- [ ] Consider using a `src/` directory to contain code such that the root level directory only contains non-code elements such as the Makefile, README, and LICENSE
- [x] Remove the `dependencies.txt`, this is not Python where a `pip install -r requirements.txt` will install these elements so list the dependencies in the README (which would make the file redundant and hence it should then be removed)
- [x] Add a description to the repo on GitHub and tag it accordingly the increase visibility
- [ ] Set up Zenodo integration, tag with semantic versioning, and cut a release based on the semantic versioned tag
- [x] Add badges to the repo: Zenodo, Travis/Actions, and JOSS paper status
- [ ] Add executable `examples/` which read in real data and show real results (these can be co-opted or split from `test/`)\*

\* Examples are for showing the user what to expect, tests are for preventing feature regression so I do not see the two as equal, however there is no definite functional the two cannot be linked in some manner as long as the examples never break and the tests are able to break should a regression occur.

**Comment by rhagenson** [comment]
Authorship fixed on https://github.com/thecodingdoc/neep/commit/e6746bee4c17b95aeb6d099c0daf36fe56deee5a

**Comment by rhagenson** [comment]
License renamed to make it easier to find on https://github.com/thecodingdoc/neep/commit/c082b7773bf7d309191a844e346442f936933adb

**Comment by scwest** [comment]
Considering the complexity of the algorithm and the expected unit outputs, I don't think automated unit testing is optimal here. Under the JOSS review criteria, it is acceptable to have a list of commands for testing the code. We had added this to the README.

**Comment by rhagenson** [comment]
@scwest, that is your decision to make.

**Comment by rhagenson** [comment]
References fixed on https://github.com/thecodingdoc/neep/commit/98621b7ba679d298b7c725ac26883333a444c0a9

**Comment by scwest** [comment]
I have tagged the items that I'll complete in the original comment. Thank you Ryan for your helpful review and suggestions!

**Comment by rhagenson** [comment]
@scwest, sounds good. Glad to help!
